# Generated by Django 6.1.1 on 2026-09-07 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('PARENT', 'Parent'), ('CHILD', 'Child')], max_length=6)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chores.family')),
                ('user', models.OneToOneField(blank=True, help_text='Parents only. Children do not have login credentials.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['family', 'role', 'display_name'],
                'constraints': [models.UniqueConstraint(fields=('family', 'display_name'), name='unique_display_name_per_family'), models.CheckConstraint(condition=models.Q(('role', 'PARENT'), ('user__isnull', True), _connector='OR'), name='children_have_no_user_account')],
            },
        ),
    ]
