# Generated by Django 6.1.1 on 2026-09-07 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('points', models.PositiveIntegerField(help_text='Base points credited to the child once a parent approves it.')),
                ('kind', models.CharField(choices=[('ROUTINE', 'Routine'), ('BOUNTY', 'Bounty')], default='ROUTINE', max_length=7)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='chores.family')),
            ],
            options={
                'ordering': ['family', 'kind', 'title'],
                'constraints': [models.UniqueConstraint(fields=('family', 'title'), name='unique_chore_title_per_family')],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.PositiveIntegerField(help_text='Points deducted from the child when they redeem this.')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='chores.family')),
            ],
            options={
                'ordering': ['family', 'cost', 'name'],
                'constraints': [models.UniqueConstraint(fields=('family', 'name'), name='unique_reward_name_per_family')],
            },
        ),
    ]
