# Generated by Django 6.1.1 on 2026-09-07 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_chore_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='The Monday the week starts on.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=8)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'PARENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='chores.profile')),
                ('child', models.ForeignKey(limit_choices_to={'role': 'CHILD'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='chores.profile')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='chores.chore')),
            ],
            options={
                'ordering': ['-week_start', 'child', 'chore'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Positive to earn, negative to spend.')),
                ('reason', models.CharField(choices=[('CHORE', 'Chore approved'), ('REWARD', 'Reward redeemed')], max_length=6)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entry', to='chores.choreassignment')),
                ('child', models.ForeignKey(limit_choices_to={'role': 'CHILD'}, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='chores.profile')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='chores.reward')),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='choreassignment',
            constraint=models.UniqueConstraint(fields=('chore', 'week_start'), name='one_holder_per_chore_per_week'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('points', 0), _negated=True), name='ledger_entry_moves_points'),
        ),
    ]
